// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  newlineBracketed = 7,
  newlineEmpty = 8,
  newline = 9,
  eof = 10,
  Comment = 1,
  Main = 3,
  VariableName = 4,
  AssignOp = 5
